name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '19.x', '20.x']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Set Global TypeScript
        run: npm install -g typescript

      - name: Build TypeScript
        run: tsc --project tsconfig.json

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '19.x', '20.x']

    env:
      ETHERSCANKEY: ${{ secrets.ETHERSCANKEY }}
      RPCURL: ${{ secrets.RPCURL }}
      EXP_URL: 'https://arbiscan.io'

    timeout-minutes: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm i

      - name: Test Running
        run: npm run test
